### PR TITLE
data for vdW params

### PR DESCRIPTION
**Pull request by loriab**
It'd be nice to offer up vdW radii along with covalent radii. here's the data. if anyone wants to write the interface before I get to it, you're welcome.

### CODE REVIEW

**Comment by dgasmith** [comment]
Should this be merged?

**Comment by loriab** [comment]
Neutral. I’d merged I can make an issue in case someone wants to tackle the interface. I mostly didn’t want to lose the file.

**Comment by loriab** [comment]
@stvogt is claiming this task.

**Comment by loriab** [comment]
Superseded by #127

**Pull request closed without merging**
