### PR TITLE
`which_import` now handles submodules correctly

### PR DESCRIPTION
**Pull request by dotsdl**
## Description

<strike>For checking if OpenMM exists in the environment, we need to feed
"simtk.openmm" to `importlib.util.find_spec`. This will work by actually
importing `simtk`, which in the case of OpenMM not being present raises
a `ModuleNotFoundError`.

This PR handles the case in which this `ModuleNotFoundError` is raised.</strike>

For checking if OpenMM exists in the environment, we need to feed "openmm" with `package="simtk"` to `importlib.util.find_spec`. This PR adds a new keyword arg `package` to `which_import` in order to pass this through to `find_spec`.

## Status
- [ ] Changelog updated
- [ ] Ready to go

### CODE REVIEW

**Comment by dotsdl** [comment]
This is currently blocking MolSSI/QCEngine#151.

**Comment by loriab** [comment]
Hadn't thought about this case. Reading through [`find_spec`](https://docs.python.org/3/library/importlib.html#importlib.util.find_spec), would it be cleaner if we passed `package` arg through, so you could call `which_import("openmm", package=simtk)`?

**Comment by dotsdl** [comment]
@loriab good catch! I'll give that a try.

**Comment by dotsdl** [comment]
@loriab this appears to have the desired effect. Thanks!

**Pull request merged**
