### PR TITLE
dipole as array

### PR DESCRIPTION
**Pull request by loriab**
## Description
Allow array serialization of dipoles. Venture a quadrupole.

## Status

- [x] Code base linted
- [x] Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
This is needed for https://github.com/psi4/psi4/pull/1351, so no hurry (and quadrupole is optional), but I promote this for next release.

**Comment by dgasmith** [comment]
I would want to run the full stack on this, but should be fine.

**Comment by loriab** [comment]
Nothing like working against oneself. I can testify that your concern is valid and QCF *does not* at present like dipole arrays. This has been why snowflake+DDD hasn't been working for me 
```
      File "/home/psilocaluser/toolchainconda/envs/py37/lib/python3.7/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/home/psilocaluser/toolchainconda/envs/py37/lib/python3.7/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type ndarray is not JSON serializable
    [SQL: UPDATE result SET molecule=%(molecule)s, keywords=%(keywords)s, return_result=%(return_result)s, properties=%(properties)s WHERE result.id = %(result_id)s]
    [parameters: [{'molecule': '1', 'keywords': '1', 'properties': {'calcinfo_nbasis': 48, 'calcinfo_nmo': 48, 'calcinfo_nalpha': 10, 'calcinfo_nbeta': 10, 'calcinfo_n ... (679 characters truncated) ... 441873569654494,  0.0224840436976431,  0.                ],
           [-0.0229027442233398,  0.0443014057178189,  0.                ]]), 'result_id': 1}]]
[E 200210 12:58:29 web:2246] 500 POST /queue_manager (::1) 32.64ms
```
It's fine so long as psi's schema runner filters out *poles before they can hit qcf. Not an urgent problem.

**Comment by dgasmith** [comment]
We store properties as JSON for fast lookup, but this currently precludes storying NumPy arrays in some circumstances. Let me look into it.

**Comment by loriab** [comment]
Thanks. I couldn't find an obvious place where qcf was treating properties differently from wavefunctionproperties.

Since qcf cares about storage (and multipoles can be 90% redundant in full 2^order form), it may be that QCSchema should officially have the full/compressed debate about storing multipoles before doing much work. Choices are (i) current, compressed only; (ii) full redundant; (iii) compressed plus expanding formula upon access.

**Comment by loriab** [comment]
I think this is what qcf needs. If so, let me know, and I'll see about psi adjustments.

**Comment by loriab** [comment]
The ddd/snowflake demo that was so unhappy with the earlier version of this PR now is content. Let me patch up the p4 PRs before merging this one, though.

EDIT: checked against qcf master

**Pull request merged**
