### PR TITLE
Update Change Log for 0.5.0

### PR DESCRIPTION
**Pull request by Lnaden**
Also bumps min Pydantic version to avoid bug from pydantic 0.30

### CODE REVIEW

**Comment by Lnaden** [comment]
Is this the pytest 5+ changes to the error handling?

**Comment by dgasmith** [comment]
Ugh yea.. should be `e.value`.

**Comment by Lnaden** [comment]
This should fix the Pytest issues, but I think there is still an actual issue in `test_pubchem_multiout_g` throwing an error regarding the Choices that PubChem is returning (I think)

**Comment by Lnaden** [comment]
I also verified that this works for Pytest 4.0+ and does not break anything downstream (i.e. Fractal)

**Comment by dgasmith** [comment]
Looks like pubchem may have changed their interface slightly.

**Comment by dgasmith** [comment]
I think I patched this.

**Comment by Lnaden** [comment]
Probably, from what I can tell, the molecule we were using just isn't coming up in the search. There is also a mismatch between results from the direct search of the word `tropolone` on the website vs what comes up when we use the URL in the `pubchem.py` file. Might be a fluke?

**Comment by dgasmith** [comment]
I think they just changed their database. It happens from time to time.

**Comment by loriab** [comment]
Finding good example for pubchem is tricky and can change over time. Don’t feel need to preserve too strongly.

**Comment by Lnaden** [comment]
Good to know, on both fronts. Thanks.

**Pull request merged**
