### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by loriab**

### CODE REVIEW

**Review by bennybp — APPROVED** [review]
Travis is still listed as an integration. Does that need to be removed?

**Comment by loriab** [comment]
[here](https://github.com/MolSSI/QCElemental/blob/bcc7a282e18443b4b91b448cbdd35ff7b5c7a168/devtools/README.md#continuous-integration)? that's cookiecutter boilerplate, and the appveyor has never been true. I can adapt it.

**Comment by bennybp** [comment]
oh no, outside of the PR in the repo settings: https://github.com/MolSSI/QCElemental/settings/installations

**Comment by loriab** [comment]
I don't really care about the travis integration in Settings. Leaving it makes it easier to turn travis-ci back on someday if needed.

**Pull request merged**
