### PR TITLE
more options from to_string()

### PR DESCRIPTION
**Pull request by loriab**
- [x] compute mol keywords close to source for gamess
- [ ] compute mol keywords close to source for nwchem
- [x] yapf Molecule Schema

### CODE REVIEW

**Comment by dgasmith** [comment]
Hey, I might have fixed Codecov!

**Comment by dgasmith** [comment]
@loriab Merge when ready.

**Comment by dgasmith** [comment]
Sorry, introduced a conflict here. +1 for YAPFing this file.

**Comment by loriab** [comment]
np. I'm just waiting to see if cfour will need changes, too.

**Pull request merged**
