### PR TITLE
from_data to dtype=2

### PR DESCRIPTION
**Pull request by loriab**
(1 commit)

could cause problems downstream

needs rebase after #42 merged

### CODE REVIEW

**Comment by dgasmith** [comment]
Can you rebase this for the history?

**Comment by loriab** [comment]
Didn't mean for this to supersede #42, unless you're confident it's harmless to downstream. Which do you want to proceed with?

**Comment by dgasmith** [comment]
It isn't completely harmless downstream as hashes change, but we need it in to start computing I think.

**Comment by loriab** [comment]
ok, rebased. clean pass locally, so clear for rev/merge after CI

**Pull request merged**
