### PR TITLE
Replaces deprecated numpy dtypes

### PR DESCRIPTION
**Pull request by Andrew-AbiMansour**
## Description

Replaces deprecated data types np.float/np.int/np.bool with native float/int/bool.
See [Notes](https://numpy.org/devdocs/release/1.20.0-notes.html) in v1.20.0 on Deprecations.

## Status

- [x] Code base linted
- [x] Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
Thanks very much. I think your changes are fine, but I wish I could read more about: "In many cases, it may have been intended to use the types from the third column. Be aware that use of these types may result in subtle but desirable behavior changes." I'll see if I can find more info.

**Review by loriab — APPROVED** [review]
I've tested these changes, and they're fine. And I can't find any more info on the subtle benefits, so let's go with it. I'll know what to suspect if problem turn up. Thanks for the PR!

**Comment by mattwthompson** [comment]
I think a couple were missed - (see https://github.com/mattwthompson/QCElemental/commit/7c5bf8045c8c8aa7ed4e617618de78b1bed561e3) but installing from source removes the deprecations warnings that are printed from the release build, at least for the part of the API we use.

**Comment by loriab** [comment]
whoops, I found a couple more than the initial PR but missed those. go ahead and PR your branch, so as to polish off. thanks.

**Pull request merged**
